### ISSUE TITLE
Error on homepage when not logged in

### ISSUE THREAD

**Issue by paranoodle** [yibnl/Teaching-HEIGVD-AMT-2015-Project#2]
If trying to access the /GamY/pages/applications page while not logged in, we're redirected to the homepage but the statistic values are missing.
![screenshot from 2015-10-09 10 46 50](https://cloud.githubusercontent.com/assets/2650399/10389585/2b78f908-6e73-11e5-9f14-b5810647d243.png)

**Comment by wasadigi** [comment]
Do you know how to solve the issue or are you looking for help?

**Comment by paranoodle** [comment]
We think we know, we posted an issue as a way to track it and remember to fix it since we didn't get to do so during today's lab.
